### ISSUE TITLE
VS 2022: Context Menus Stopped Responding

### ISSUE THREAD

**Issue by rmcgold2** [Exafunction/CodeiumVisualStudio#119]
Today, this error message started showing up in VS 2022. Uninstalling and reinstalling the extension did not resolve the issue. Clearing the extension cache also did not resolve the issue. Chat works, but the context menus result in the error in the Extensions output:

System.InvalidOperationException: Duplicate field-number detected; 6 on: CodeiumVS.Packets.GetChatMessageRequest
   at ProtoBuf.Internal.Serializers.TypeSerializer`1.Init(Int32[] fieldNumbers, IRuntimeProtoSerializerNode[] serializers, MethodInfo[] baseCtorCallbacks, Boolean isRootType, Boolean useConstructor, Boolean assertKnownType, CallbackSet callbacks, Type constructType, MethodInfo factory, SerializerFeatures features) in /_/src/protobuf-net/Internal/Serializers/TypeSerializer.cs:line 222
   at ProtoBuf.Internal.Serializers.TypeSerializer.Create(Type forType, Int32[] fieldNumbers, IRuntimeProtoSerializerNode[] serializers, MethodInfo[] baseCtorCallbacks, Boolean isRootType, Boolean useConstructor, Boolean assertKnownType, CallbackSet callbacks, Type constructType, MethodInfo factory, Type rootType, SerializerFeatures features) in /_/src/protobuf-net/Internal/Serializers/TypeSerializer.cs:line 22
   at ProtoBuf.Meta.MetaType.BuildSerializer() in /_/src/protobuf-net/Meta/MetaType.cs:line 619
   at ProtoBuf.Meta.MetaType.get_Serializer() in /_/src/protobuf-net/Meta/MetaType.cs:line 460
   at ProtoBuf.Meta.RuntimeTypeModel.<GetServicesSlow>g__GetServicesImpl|88_0(RuntimeTypeModel model, Type type, CompatibilityLevel ambient) in /_/src/protobuf-net/Meta/RuntimeTypeModel.cs:line 1033
   at ProtoBuf.Meta.RuntimeTypeModel.GetServicesSlow(Type type, CompatibilityLevel ambient) in /_/src/protobuf-net/Meta/RuntimeTypeModel.cs:line 999
   at ProtoBuf.Meta.RuntimeTypeModel.GetServices[T](CompatibilityLevel ambient) in /_/src/protobuf-net/Meta/RuntimeTypeModel.cs:line 975
   at ProtoBuf.Meta.RuntimeTypeModel.GetSerializerCore[T](CompatibilityLevel ambient) in /_/src/protobuf-net/Meta/RuntimeTypeModel.cs:line 965
   at ProtoBuf.Meta.TypeModel.GetSerializer[T](TypeModel model, CompatibilityLevel ambient) in /_/src/protobuf-net.Core/Meta/TypeModel.cs:line 1439
   at ProtoBuf.ProtoWriter.WriteMessage[T](State& state, T value, ISerializer`1 serializer, PrefixStyle style, Boolean recursionCheck) in /_/src/protobuf-net.Core/ProtoWriter.cs:line 263
   at ProtoBuf.ProtoWriter.State.WriteMessage[T](Int32 fieldNumber, SerializerFeatures features, T value, ISerializer`1 serializer) in /_/src/protobuf-net.Core/ProtoWriter.State.WriteMethods.cs:line 350
   at proto_1(State& , WebServerRequest )
   at ProtoBuf.ProtoWriter.State.SerializeRoot[T](T value, ISerializer`1 serializer) in /_/src/protobuf-net.Core/ProtoWriter.State.WriteMethods.cs:line 639
   at ProtoBuf.Serializer.Serialize[T](Stream destination, T instance, Object userState) in /_/src/protobuf-net/Serializer.Serialize.cs:line 33
   at CodeiumVS.WebChatServer.Send(WebServerRequest request, WebSocket ws) in C:\Users\saransh\Desktop\CodeiumVisualStudio\CodeiumVS\LanguageServer\LanguageServerController.cs:line 365
   at CodeiumVS.LanguageServerController.<ExplainCodeBlockAsync>d__7.MoveNext() in C:\Users\saransh\Desktop\CodeiumVisualStudio\CodeiumVS\LanguageServer\LanguageServerController.cs:line 193
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CodeiumVS.Commands.CommandExplainCodeBlock.<ExecuteAsync>d__1.MoveNext() in C:\Users\saransh\Desktop\CodeiumVisualStudio\CodeiumVS\Commands.cs:line 292
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Community.VisualStudio.Toolkit.BaseCommand.<>c__DisplayClass8_0.<<Execute>b__0>d.MoveNext()

Here is the debug output:

{
  "diagnostics": {
    "url": "http://127.0.0.1:54135/?api_key=8c9106bf-7404-4ad2-9cfb-bf524f7554a5&extension_name=Codeium&extension_version=1.8.81&ide_name=vscode&ide_version=17.11.35303.130&locale=en-US&ide_telemetry_enabled=true&app_name=Visual%20Studio&web_server_url=ws://127.0.0.1:54134&has_dev_extension=false&has_index_service=true&open_file_pointer_enabled=true&diff_view_enabled=true&insert_at_cursor_enabled=true&has_enterprise_extension=false",
    "connection": {
      "status": "READY",
      "error": {}
    },
    "isChatEnabled": true,
    "handshake": {
      "disabledTelemetry": false,
      "ignoreChatTelemetrySetting": false
    },
    "params": {
      "ideTelemetryEnabled": true,
      "ready": true,
      "apiKey": "8c9106bf-7404-4ad2-9cfb-bf524f7554a5",
      "extensionName": "Codeium",
      "extensionVersion": "1.8.81",
      "ideName": "vscode",
      "ideVersion": "17.11.35303.130",
      "locale": "en-US",
      "hasDevExtension": false,
      "hasEnterpriseExtension": false,
      "hasIndexService": true,
      "appName": "Visual Studio",
      "webServerUrl": "ws://127.0.0.1:54134",
      "diffViewEnabled": true,
      "openFilePointerEnabled": true,
      "insertAtCursorEnabled": true
    },
    "data": {
      "numMessages": 0
    },
    "bridge": {
      "bridgeType": "null"
    },
    "health": {
      "checkStatus": 200,
      "error": {}
    }
  },
  "logs": [
    "[WARN] 2024-9-16 23:55:24.945 [react-tooltip] Element with id 'react-tooltip-core-styles' already exists. Call `removeStyle()` first",
    "[WARN] 2024-9-16 23:55:24.945 [react-tooltip] Element with id 'react-tooltip-base-styles' already exists. Call `removeStyle()` first",
    "[WARN] 2024-9-16 23:55:24.950 [react-tooltip] Element with id 'react-tooltip-core-styles' already exists. Call `removeStyle()` first",
    "[WARN] 2024-9-16 23:55:24.950 [react-tooltip] Element with id 'react-tooltip-base-styles' already exists. Call `removeStyle()` first",
    "[LOG] 2024-9-16 23:55:24.974 Error constructing delta SyntaxError: Unexpected end of JSON input",
    "[WARN] 2024-9-17 0:2:34.651 [react-tooltip] Element with id 'react-tooltip-core-styles' already exists. Call `removeStyle()` first",
    "[WARN] 2024-9-17 0:2:34.651 [react-tooltip] Element with id 'react-tooltip-base-styles' already exists. Call `removeStyle()` first",
    "[WARN] 2024-9-17 0:2:34.713 [react-tooltip] Element with id 'react-tooltip-core-styles' already exists. Call `removeStyle()` first",
    "[WARN] 2024-9-17 0:2:34.713 [react-tooltip] Element with id 'react-tooltip-base-styles' already exists. Call `removeStyle()` first"
  ]
}

**Comment by rmcgold2** [comment]
I'm having the same issue in a different environment. In my case, errors are still appearing in the Extension output. Codeium Chat works when interacting with it directly. Extension errors occur when using any of the context menu options from within a file.
