### ISSUE TITLE
Codeium Crash

### ISSUE THREAD

**Issue by GTechMicah** [Exafunction/CodeiumVisualStudio#62]
Hey Guys, I think your extension is really cool, the only thing that would keep from using it (and which has caused me to remove it from visual studio at least until this gets fixed) is this crash, which occurs multiple times per day, sometimes repeatedly right right after the previous crash. The crash freezes visual studio before causing it to restart, which is a real annoyance. I'm opening this in another pr because the stack trace and exception are different from the other crash.

I know it is caused by this extension because it only started after I installed it and stopped after I removed it.

I'm using it with VB.Net winforms and class library projects, in visual studio 2022 version 17.9.2, I have Devexpress's CodeRush extension also installed.

Here's event viewer details:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.ThrowIfInvalid()
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.get_Start()
   at Microsoft.VisualStudio.Text.Editor.Implementation.TextViewLineCollection.FindTextViewLineIndexContainingBufferPosition(Microsoft.VisualStudio.Text.SnapshotPoint)
   at Microsoft.VisualStudio.Text.Editor.Implementation.TextViewLineCollection.GetCharacterBounds(Microsoft.VisualStudio.Text.SnapshotPoint)
   at CodeiumVS.SuggestionTagger.UpdateAdornment(Microsoft.VisualStudio.Text.Editor.IWpfTextView, System.String, Int32)
   at CodeiumVS.SuggestionTagger.Update()
   at CodeiumVS.CodeiumCompletionHandler+<GetCompletion>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
(https://github.com/Exafunction/CodeiumVisualStudio/issues/new#) <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-03-07T16:42:32.7837898Z" /> 
  <EventRecordID>200698</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>XXX</Computer> 
  <Security /> 
  </System>
(https://github.com/Exafunction/CodeiumVisualStudio/issues/new#) <EventData>
  <Data>Application: devenv.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.ObjectDisposedException at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.ThrowIfInvalid() at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.get_Start() at Microsoft.VisualStudio.Text.Editor.Implementation.TextViewLineCollection.FindTextViewLineIndexContainingBufferPosition(Microsoft.VisualStudio.Text.SnapshotPoint) at Microsoft.VisualStudio.Text.Editor.Implementation.TextViewLineCollection.GetCharacterBounds(Microsoft.VisualStudio.Text.SnapshotPoint) at CodeiumVS.SuggestionTagger.UpdateAdornment(Microsoft.VisualStudio.Text.Editor.IWpfTextView, System.String, Int32) at CodeiumVS.SuggestionTagger.Update() at CodeiumVS.CodeiumCompletionHandler+<GetCompletion>d__14.MoveNext() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() at System.Threading.ThreadPoolWorkQueue.Dispatch()</Data> 
  </EventData>
  </Event>

```

I hope you guys can find a way to fix it. If you need any other details, please feel free to let me know.
Thank You

**Comment by fortenforge** [comment]
Are you on the latest version of the plugin (1.8.6)? We fixed a number of crashes in this release.

**Comment by GTechMicah** [comment]
Oh, no I wasn't, I installed it on the 5th of this month but 1.8.0 got installed. Thank You for bringing that to my attention @fortenforge, I appreciate it, I'll update it and let you know if I get the crash again.

**Comment by GTechMicah** [comment]
Hello @fortenforge, I got that crash again even with the update. I know it happens when I'm writing code in visual studio.

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.ThrowIfInvalid()
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.get_VisibilityState()
   at Microsoft.VisualStudio.Text.Editor.Implementation.TextViewLineCollection.Microsoft.VisualStudio.Text.Editor.IWpfTextViewLineCollection.get_FirstVisibleLine()
   at CodeiumVS.InlineGreyTextTagger.MarkDirty()
   at CodeiumVS.SuggestionTagger.MarkDirty()
   at CodeiumVS.SuggestionTagger.Update()
   at CodeiumVS.CodeiumCompletionHandler+<GetCompletion>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   


Here's my codeium debug info:
'''json
{
  "url": "http://127.0.0.1:50991/?api_key=1e406eb9-3a3f-4271-928f-0cc7e65d93b0&extension_name=Codeium&extension_version=1.8.6&ide_name=visual_studio&ide_version=17.9.34701.34&locale=en-US&ide_telemetry_enabled=true&app_name=Visual%20Studio&web_server_url=ws://127.0.0.1:50990&has_dev_extension=false&has_index_service=true&open_file_pointer_enabled=true&diff_view_enabled=true&insert_at_cursor_enabled=true&has_enterprise_extension=false",
  "connection": {
    "status": "READY",
    "error": {}
  },
  "isChatEnabled": true,
  "handshake": {
    "disabledTelemetry": false,
    "ignoreChatTelemetrySetting": false
  },
  "params": {
    "ideTelemetryEnabled": true,
    "ready": true,
    "apiKey": "1e406eb9-3a3f-4271-928f-0cc7e65d93b0",
    "extensionName": "Codeium",
    "extensionVersion": "1.8.6",
    "ideName": "visual_studio",
    "ideVersion": "17.9.34701.34",
    "locale": "en-US",
    "hasDevExtension": false,
    "hasEnterpriseExtension": false,
    "hasIndexService": true,
    "appName": "Visual Studio",
    "webServerUrl": "ws://127.0.0.1:50990",
    "diffViewEnabled": true,
    "openFilePointerEnabled": true,
    "insertAtCursorEnabled": true
  },
  "data": {
    "numMessages": 17
  },
  "bridge": {
    "bridgeType": "null"
  },
  "health": {
    "checkStatus": 200,
    "error": {}
  }
}
```

**Comment by fortenforge** [comment]
This crash should be fixed in 1.8.14.

**Comment by GTechMicah** [comment]
Sorry to report @fortenforge, it did it again in 1.8.14

**Comment by fortenforge** [comment]
Do you have a stack trace?

**Comment by GTechMicah** [comment]
Sure, so basically every time, first visual studio freezes up completely and then it crashes, although sometimes [when codeium is disabled] my visual studio will freeze up completely for a few seconds **but it recovers from it after a few seconds**, but when codeium is enabled, VS freezes completely to any input and it lasts a noticeably longer before VS crashes and reboots.

This is what I'm seeing in the event viewer:
![image](https://github.com/Exafunction/CodeiumVisualStudio/assets/108148042/affe58fe-7968-4005-a649-d40a18216844)

Here's the stack traces for those errors:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.ThrowIfInvalid()
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.get_VisibilityState()
   at Microsoft.VisualStudio.Text.Editor.Implementation.TextViewLineCollection.Microsoft.VisualStudio.Text.Editor.IWpfTextViewLineCollection.get_FirstVisibleLine()
   at CodeiumVS.SuggestionTagger.MarkDirty()
   at CodeiumVS.SuggestionTagger.Update()
   at CodeiumVS.CodeiumCompletionHandler+<GetCompletion>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


And also:
Faulting application name: devenv.exe, version: 17.9.34701.34, time stamp: 0x65e1f90d
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3996, time stamp: 0xb756c9ff
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process id: 0x60c4
Faulting application start time: 0x01da7bb96f8d2809
Faulting application path: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: e7ce571b-a881-44d8-9f74-0c3d57ed99c8
Faulting package full name: 
Faulting package-relative application ID: 


I'm using visual studio's blue theme if that matters at all.

**Comment by GTechMicah** [comment]
I just noticed that there is another event, not directly labeled as an error right after the visual studio crash logs for windows error reporting, do you want any of the referenced files?
 
Fault bucket 1729781190157475264, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: devenv.exe
P2: 17.9.34701.34
P3: 65e1f90d
P4: Microsoft.VisualStudio.Platform.VSEditor
P5: 17.9.187.38890
P6: ca0ccd69
P7: 196b
P8: 12
P9: System.ObjectDisposedException
P10: 

Attached files:
\\?\C:\Users\XXX\AppData\Roaming\microsoft\visualstudio\17.0_bad6b01f\activitylog.xml
\\?\C:\Users\XXX\AppData\Roaming\microsoft\visualstudio\17.0_bad6b01f\activitylog.setup.xml
\\?\C:\Users\XXX\AppData\Local\microsoft\visualstudio\17.0_bad6b01f\devenv.exe.config
\\?\C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.isolation.ini
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4678.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER912E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER913F.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER914C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER917C.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_devenv.exe_421baf24486b530526681a8f630e01ee95688_f7e34bca_630cfb73-48fc-4995-95d8-0b537584c28b

Analysis symbol: 
Rechecking for solution: 0
Report Id: e7ce571b-a881-44d8-9f74-0c3d57ed99c8
Report Status: 268435456
Hashed bucket: 7484232ae8bf022838016ad3e27d1dc0

**Comment by GTechMicah** [comment]
Hey @fortenforge, it's possible that this issue is fixed as I haven't seen it in a bit. It's also possible that there may have been a coderush issue that caused that last crash.

Thanks anyways, the extension has been working for me.
