### ISSUE TITLE
language server port not found on code-server

### ISSUE THREAD

**Issue by Weredok** [Exafunction/CodeiumVisualStudio#73]
Hey! I using code-server and want to use codeium here, but window with codeium chat is infinity loading, all commands like `Codeium: Command` getting error `Command 'Codeium: Command ✨' resulted in an error
command 'codeium.openCodeiumCommand' not found` . I viewed output from extension but still don't know how can i fix it? You don't have published language server code and normally it downloading when user closing all editors, but how i can trigger that on code-server?

Console output:
```sh
2024-04-14 16:10:23.281 [INFO]: No proxy settings found
2024-04-14 16:10:24.786 [INFO]: Creating manager directory: /tmp/ea8f4d2b-3249-445e-b082-b4f07f0d8e28/codeium/manager
2024-04-14 16:10:26.233 [INFO]: Using cached LS with valid crc32: /home/container/.local/share/code-server/extensions/codeium.codeium-1.8.18-universal/dist/2614e1f78c5188e3091a05c11a4ff23e69f4a5c9/language_server_linux_x64
2024-04-14 16:10:26.268 [INFO]: Language server started
2024-04-14 16:10:26.598 [INFO]: [Language Server (stderr)]:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6f32ff0]

goroutine 1 [running]:
2024-04-14 16:10:26.602 [INFO]: [Language Server (stderr)]:
main.main()
	exa/cmd/language_server/main.go:492 +0xf50
2024-04-14 16:10:26.606 [INFO]: Language server exited with code 2
2024-04-14 16:11:26.297 [ERROR]: Language server port file not found in /tmp/ea8f4d2b-3249-445e-b082-b4f07f0d8e28/codeium/manager after 60s
```

**Comment by SA-anet** [comment]
Facing the same issue.

**Comment by luthien945** [comment]
got same issue after update to  1.8.73.
error log from extension output:
I0702 10:09:09.804583 21081 client.go:589] [DEBUG] GET https://server.codeium.com/exa.api_server_pb.ApiServerService/GetCompletions
I0702 10:09:10.992181 21081 unleash.go:90] Initializing Unleash
I0702 10:09:10.994781 21081 unleash.go:110] Successfully initialized Unleash
E0702 10:09:10.995093 21081 unleash.go:60] Unleash error: Get "https://unleash.codeium.com/api/client/features": dial tcp 35.223.238.178:443: protocol not available
E0702 10:09:10.995112 21081 unleash.go:60] Unleash error: Post "https://unleash.codeium.com/api/client/register": dial tcp 35.223.238.178:443: protocol not available
E0702 10:09:11.006913 21081 client_manager.go:270] Metadata is nil when trying to refresh user JWT
E0702 10:09:11.008899 21081 api_server_client.go:242] GetConfig error: unavailable: dial tcp 35.223.238.178:443: protocol not available
F0702 10:09:11.009008 21081 main.go:602] Language server failed - unavailable: dial tcp 35.223.238.178:443: protocol not available
(1) attached stack trace
  -- stack trace:
  | github.com/Exafunction/Exafunction/exa/language_server.CreateLanguageServerAndServe
  | 	exa/language_server/server.go:167
  | [...repeated from below...]
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/Exafunction/Exafunction/exa/language_server.initServers
  | 	exa/language_server/server.go:353
  | github.com/Exafunction/Exafunction/exa/language_server.CreateLanguageServerAndServe
  | 	exa/language_server/server.go:165
  | main.main
  | 	exa/cmd/language_server/main.go:600
  | runtime.main
  | 	GOROOT/src/runtime/proc.go:267
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1650
Wraps: (3) unavailable
Wraps: (4) dial tcp 35.223.238.178:443
Wraps: (5) protocol not available
Error types: (1) *withstack.withStack (2) *withstack.withStack (3) *connect.Error (4) *net.OpError (5) syscall.Errno
(VSCode) 2024-07-02 10:09:24.207 [ERROR]: Language server port file not found in /tmp/40314578-527f-408a-85ec-5e1d36508f24/codeium/manager after 60s
I0702 10:09:24.613042 20908 main.go:281] Failed to get random ports within 15 seconds
I0702 10:09:24.614424 20908 cmd_wrapper.go:267] LanguageServer exited with: exit code: 1
F0702 10:09:24.615520 20908 main.go:174] Exceeded maximum number of connection failures 4
(VSCode) 2024-07-02 10:09:24.624 [INFO]: Language server exited with code 1
